# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb42d6bff3c3a8ccc9e9f29dcc90bd8ddc02959a315cb72dc527c2b46206ab4b3855cf311101a1469b04c7c1ffc42d69edeb3e793beec2654e34a03f7d129909

test:
  secret_key_base: 27369646307818dfc5f424481c9980ae792ca293665c4f8ac9a4d94800951f6f05cb095dc52bce15cb693581f69ea63c6f0dc00e8842dc19ac0ff627d0176e52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
